# Generated by Django 2.2.7 on 2020-02-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='slug',
        ),
    ]
