# Generated by Django 2.2.7 on 2020-02-12 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_remove_flight_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveller_ticket', to='sampleapp.Ticket'),
        ),
    ]
