# Generated by Django 2.2.7 on 2020-02-12 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_auto_20200212_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_model',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
