# Generated by Django 2.2.7 on 2020-02-14 12:49

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0005_continent_country_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='continent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='sampleapp.Country', verbose_name='Country'),
        ),
    ]
