# Generated by Django 2.2.7 on 2020-02-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0008_auto_20200214_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
