# Generated by Django 2.2.7 on 2020-01-23 13:26

from django.db import migrations, models
import django.db.models.deletion
import tours.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'destination',
                'verbose_name_plural': 'destinations',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(max_length=200)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('description', models.TextField()),
                ('price_adt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_chd_one', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_chd_two', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_inf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('stars', models.IntegerField()),
                ('image_main', models.ImageField(blank=True, upload_to=tours.models.program_directory_path)),
                ('image_1', models.ImageField(blank=True, upload_to=tours.models.program_directory_path)),
                ('image_2', models.ImageField(blank=True, upload_to=tours.models.program_directory_path)),
                ('image_3', models.ImageField(blank=True, upload_to=tours.models.program_directory_path)),
                ('image_4', models.ImageField(blank=True, upload_to=tours.models.program_directory_path)),
                ('image_5', models.ImageField(blank=True, upload_to=tours.models.program_directory_path)),
                ('image_6', models.ImageField(blank=True, upload_to=tours.models.program_directory_path)),
                ('flight', models.CharField(max_length=50)),
                ('flight_detail', models.TextField()),
                ('available_front_page', models.BooleanField(default=True)),
                ('available_programs_page', models.BooleanField(default=True)),
                ('available_lastminut_page', models.BooleanField(default=True)),
                ('available_tours_page', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_programs', to='tours.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cit_programs', to='tours.City')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='des_programs', to='tours.Destination')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ('arrival_date',),
            },
        ),
    ]
