# Generated by Django 2.2.7 on 2020-03-27 15:04

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200327_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=tours.models.program_directory_path),
        ),
        migrations.AddField(
            model_name='destination',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=tours.models.program_directory_path),
        ),
        migrations.AddField(
            model_name='destination',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=tours.models.program_directory_path),
        ),
        migrations.AddField(
            model_name='destination',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to=tours.models.program_directory_path),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=tours.models.program_directory_path),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=tours.models.program_directory_path),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=tours.models.program_directory_path),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to=tours.models.program_directory_path),
        ),
    ]
