# Generated by Django 2.2.7 on 2020-02-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200201_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'flight',
                'verbose_name_plural': 'flights',
                'ordering': ('arrival_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='airline',
            options={'ordering': ('airline_code',), 'verbose_name': 'airline', 'verbose_name_plural': 'airlines'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('flight',), 'verbose_name': 'program', 'verbose_name_plural': 'programs'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='departure_date',
        ),
        migrations.AddField(
            model_name='program',
            name='airline',
            field=models.ForeignKey(default='15.02.2019', on_delete=django.db.models.deletion.CASCADE, related_name='air_programs', to='tours.Airline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='htl_programs', to='tours.Flight'),
        ),
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Airline',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Airline'),
        ),
    ]
