# Generated by Django 2.2.7 on 2020-03-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200327_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
