# Generated by Django 2.2.7 on 2020-05-13 16:17

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20200328_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='destination', chained_model_field='destination', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cit_programs', to='tours.City'),
        ),
    ]
